### ISSUE TITLE
When installing a project, docker does not create an application zprofile

### ISSUE THREAD

**Issue by SergeyMi37** [caretdev/zprofile#1]

**Comment by daimor** [comment]
How to reproduce it?
zpm install?

**Comment by SergeyMi37** [comment]
No, not zpm, but just building docker

**Comment by SergeyMi37** [comment]
http://my-ip:8773/zprofile/index.html
gives an error message

**Comment by daimor** [comment]
There is no stage for build, it's just `docker-compose up -d` and it installs module during iris start 
probably the issue in init.db folder on windows, sh files there should have an execution flags
check `docker-compose logs iris`

This docker-compose uses FHIR, which I used to run traces, and during start 
so probably, you are just to quick, and it did not install it yet, check the logs, it should show if it's installed at all

**Comment by SergeyMi37** [comment]
Docker is going to rhel.
there is an error in the log
...
ris_1 | FHIRSERVER>
iris_1 |
iris_1 | Node: 624daaf9abcc, Instance: IRIS
iris_1 |
iris_1 | USER>
iris_1 |
iris_1 | FHIRSERVER>
iris_1 |
iris_1 | [FHIRSERVER|zprofile] Reload START (/home/irisowner/zprofile/)
iris_1 | [zprofile] Reload FAILURE
iris_1 | ERROR! Directory name '/home/irisowner/zprofile/tests/' is invalid
iris_1 | FHIRSERVER>
iris_1 | [INFO]
...

**Comment by daimor** [comment]
Ahh, I see, pushed fix
